name: Bug Report
description: File a bug report
title: "[Bug]: "
labels:
  - '[Status] Triage'
assignees:
  - Olegbstu
body:
  - type: markdown
    attributes:
      value:  >-
        For help with Neurotrauma, please use [Main page](https://github.com/OlegBSTU/Neurotrauma).

        For mod troubleshooting related to Neurotrauma, please use [Fork server](https://discord.gg/4Yku7qPCYN).

        For general modding help and support visit the [Undertow Games: baro-modding channel](https://discord.com/channels/103209684680323072/426913209602146315).
  - type: dropdown
    id: lua-version
    attributes:
      label: LuaForBarotrauma version
      options:
        - 1.0.96
        - 1.0.95
        - 1.0.94
        - 1.0.93
        - 1.0.92
        - 1.0.91
        - 1.0.90
        - 1.0.89
        - 1.0.88
        - 1.0.87
        - 1.0.86
        - 1.0.85
        - 1.0.84
    validations:
      required: true
  - type: dropdown
    id: addons-used
    attributes:
      label: Expansions in use
      multiple: true
      options:
        - "NT Symbiosis"
        - "NT Cybernetics"
        - "NT Pharmacy"
        - "Curly's NT Surgery Plus Ultra (name Pending)"
        - "Neurotrauma Tutorial Map: Mercy Hospital"
        - "NT Blahaj Plus"
        - "NT Symbiote"
        - "No expansions"
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Neurotrauma Version
      placeholder: "A1.9.6"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Log or Crash Report
      description: >-
        If you have any logs (`crash.log`, `crash-report<side>-<date>.txt`, etc...)
        Please upload the entire content in the log(s) to any paste site
        *Examples:*
         - [Github Gist](https://gist.github.com/)
         - [Hastebin](https://hastebin.com/)
         - [paste.gg](https://paste.gg/)
         - [Pastebin](https://pastebin.com/)
         - []
        Please upload your log (latest.log and/or crash report) to [Github
        Gist](https://gist.github.com/) then paste the gist url here, you
        can paste as many links as needed
      placeholder: 'http://'
  - type: textarea
    id: repro
    attributes:
      label: Reproduction steps
      description: How do you trigger this bug? Please walk us through it step by step. Add relevant screenshots if needed.
      value: |
        1. Do this
        2. Do that
        3. Crash/Bug
        ...
    validations:
      required: true
